name: mapping

dependencies:
  - pip=19.1.1
  - python=3.6.8
  - psutil
  - matplotlib
  - scikit-image
  - lightgbm=2.2.1

  - pip:
      - click==6.7
      - tqdm==4.23.0
      - pydot_ng==1.0.0
      - git+https://github.com/lucasb-eyer/pydensecrf.git
      - xgboost==0.90
      - neptune-client==0.3.0
      - neptune-contrib==0.9.2
      - imgaug==0.2.5
      - opencv_python==3.4.0.12
      - torch==0.3.1
      - torchvision==0.2.0
      - pretrainedmodels==0.7.0
      - pandas==0.24.2
      - numpy==1.16.4
      - cython==0.28.2
      - pycocotools==2.0.0
